port: 4222
monitor_port: 8222
http_port: 8222

server_name: "tnsvt-nats"

jetstream {
  store_dir: "E:\\TNSVT-V2-Architecture\\data\\nats"
}

log_file: "E:\\TNSVT-V2-Architecture\\logs\\nats.log"
logtime: true
