apiVersion: 1

providers:
  - name: 'Prometheus'
    orgId: 1
    folder: 'Prometheus'
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /etc/grafana/provisioning/datasources

dashboards:
  default:
    enabled: true
    path: /var/lib/grafana/dashboards