$env:ACCOUNT_MANAGER_URL = "http://localhost:8510"
$env:LST_TENANT_ID = "d028c9ec-6257-4d38-8a55-7ba6dd4f2b9b"
$env:LST_LOGIN = "12345678"
$env:LST_SERVER = "YourBroker-MT5"
$env:LST_PASSWORD = "change_me"
$env:LST_BROKER = "YourBroker"
$env:LST_ALIAS = "lst-main"
$env:LST_ACCOUNT_ID_FILE = "E:\TNSVT-V2-Architecture\secrets\lst_account_id"
Set-Location "E:\TNSVT-V2-Architecture"
python apps/integrations/lst-account-bootstrap/main.py
